In [1]:
import pandas as pd
import re

In [3]:
hn = pd.read_csv('hacker_news.csv')
titles = hn['title']
pattern = r'SQL'
sql_counts = titles.str.contains(pattern, flags=re.I).value_counts()
sql_counts

False    19991
True       108
Name: title, dtype: int64

In [5]:
hn_sql = hn[hn['title'].str.contains(r'\w+SQL',flags=re.I)].copy()
hn_sql

,id,title,url,num_points,num_comments,author,created_at
142,10957172,PostgreSQL: Linux VS Windows part 2,http://www.sqig.net/2016/01/postgresql-linux-v...,16,3,based2,1/23/2016 4:21
221,11544342,MemSQL (YC W11) Raises $36M Series C,http://blog.memsql.com/memsql-raises-series-c/,74,14,ericfrenkiel,4/21/2016 18:32
882,10413272,Pgmemcahe :A PostgreSQL memcache functions,https://github.com/ohmu/pgmemcache/,2,1,websec,10/19/2015 14:55
1160,10546681,How to choose an in-memory NoSQL solution: Per...,http://articles.rvncerr.org/how-to-chose-an-in...,9,4,rvncerr,11/11/2015 14:04
1197,11583183,Postgraphql: A GraphQL schema created by refle...,https://github.com/calebmer/postgraphql,217,24,craigkerstiens,4/27/2016 18:29
1370,10532855,"MI6 (SIS) Is Developing a Node.js, Angular, No...",https://recruitmentservices.applicationtrack.c...,35,47,haser_au,11/9/2015 13:24
2430,12300670,Tracker: Ingesting MySQL data at scale Part 2,https://engineering.pinterest.com/blog/tracker...,3,1,rwultsch,8/16/2016 21:08
2432,10361294,SQL for NoSQL: Couchbase N1QL Tutorial,http://query.pub.couchbase.com/tutorial/#1,9,1,porker,10/9/2015 16:38
4546,11437660,"Finally, multiple synchronous replication for ...",http://git.postgresql.org/gitweb/?p=postgresql...,8,1,snaky,4/6/2016 9:28
4568,10725042,Getting started with NoSQL databases and MongoDB,http://www.danielgynn.com/getting-started-mong...,1,1,danielgynn,12/13/2015 1:39
4616,10674187,When are we going to contribute BDR to PostgreSQL,http://blog.2ndquadrant.com/when-are-we-going-...,2,1,rachbelaid,12/4/2015 2:25
4944,10519135,SQL vs. NoSQL: you do want to have a relationa...,http://enterprisecraftsmanship.com/2015/11/06/...,16,2,vkhorikov,11/6/2015 12:41
5398,12430768,Understanding the power of data types (Postgre...,http://postgres-data-types.pvh.ca,3,1,insulanian,9/5/2016 15:21
5523,11174174,Node.js and Express Authentication Kit with My...,https://www.noodl.io/market/product/P201601091...,1,2,noodlio,2/25/2016 13:21
5654,11170360,Independent SQL-On-Hadoop Benchmark of SparkSQ...,http://blog.atscale.com/how-different-sql-on-h...,14,1,mb22,2/24/2016 21:27
5738,10484824,"Once a Year Your Data is Corrupted, Happy Hall...",https://bugs.mysql.com/bug.php?id=38455,13,2,neilellis,11/1/2015 0:10
5844,11984351,"Node-Data is unique framework to support sql,n...",https://github.com/ratneshsinghparihar/Node-Data,5,2,ratneshsingh,6/27/2016 5:33
6523,12576116,Bidirectional Replication is coming to Postgre...,http://blog.2ndquadrant.com/bdr-is-coming-to-p...,200,38,iamd3vil,9/25/2016 16:54
6532,10469304,Open-sourcing Pinterest MySQL management tools,https://engineering.pinterest.com/blog/open-so...,101,8,rwultsch,10/29/2015 4:41
7050,12329499,Live MySQL Schema Changes on RDS with Percona ...,https://github.com/mrafayaleem/percona-present...,2,1,iamspoilt,8/21/2016 5:16
7245,12142364,The Internals of PostgreSQL,http://www.interdb.jp/pg/index.html,4,1,myth17,7/22/2016 8:25
7571,12576002,A fast PostgreSQL client library for Python: 3...,https://github.com/MagicStack/asyncpg,3,1,arjun27,9/25/2016 16:33
8371,11588305,PGHoard: Tools for making PostgreSQL backups t...,http://blog.aiven.io/2016/04/postgresql-cloud-...,72,13,melor,4/28/2016 12:34
8823,10761955,PostgreSQL 9.5 RC1 Released,http://www.postgresql.org/about/news/1631/,209,36,elchief,12/19/2015 0:20
9643,11353322,"Citus Unforks from PostgreSQL, Goes Open Source",https://www.citusdata.com/blog/17-ozgun-erdoga...,763,153,jamesheroku,3/24/2016 15:02
10238,10204844,"PostgreSQL, pg_shard, and what we learned from...",https://www.citusdata.com/blog/19-ozgun/265-po...,108,18,craigkerstiens,9/11/2015 17:10
10264,11183348,PostgreSQL Indexes: First principles,http://eftimov.net/postgresql-indexes-first-pr...,240,37,craigkerstiens,2/26/2016 19:13
10478,11458621,Un-spoken complexity of NoSQL,http://pjuu.github.io/pjuu/nosql/mongo/choices...,7,1,pjuu,4/8/2016 22:33
10851,11927626,NoSQL Data Stores in Research and Practice [sl...,http://de.slideshare.net/felixgessert/nosql-da...,50,3,DivineTraube,6/18/2016 8:48
11793,11284523,MongoDB: The Frankenstein Monster of NoSQL Dat...,https://www.linkedin.com/pulse/mongodb-franken...,54,7,buffyoda,3/14/2016 18:26
12757,11683306,PostgreSQL 9.6 Beta 1 Released,http://www.postgresql.org/about/news/1668/,174,40,linuxhiker,5/12/2016 13:47
12766,12241157,Mroonga: Fast fulltext search for all language...,https://github.com/mroonga/mroonga,1,1,guifortaine,8/7/2016 5:16
12800,12542095,The 5 Stages of NoSQL,https://sookocheff.com/post/opinion/the-five-s...,33,19,soofaloofa,9/20/2016 18:43
12973,12529310,Ask HN: In what areas are NoSQL Databases bene...,NaN,74,73,rochak,9/19/2016 6:06
14132,10652254,Ask HN: Have you had to switch / compensate yo...,NaN,8,6,vishaldpatel,11/30/2015 22:09
14527,10696058,How to Create a Unique Constraint on a LoopBac...,https://wiredcraft.com/blog/unique-constraint-...,4,1,katier,12/8/2015 13:02
15089,11089907,Ask HN: Static site generation from mySql?,NaN,4,2,bigdipper,2/12/2016 19:42
15348,10458138,Show HN: Use Postgres as a zero-config NoSQL d...,https://github.com/fiatjaf/pgjson,9,3,fiatjaf,10/27/2015 14:22
15898,11608757,OVH: PaaS DB PostgreSQL,https://www.runabove.com/PaaSDBPGSQL.xml,74,37,paukiatwee,5/2/2016 1:47
16095,10319153,Fast starting MySQL Docker image suitable for ...,https://hub.docker.com/r/zanox/mysql/,1,1,yarekt,10/2/2015 15:30
16099,12267150,Need help to set ODBC MySQL driver,NaN,1,1,PatriciaTabor,8/11/2016 10:26
16135,12289975,NoSQL Databases: A Survey and Decision Guidance,https://medium.com/baqend-blog/nosql-databases...,297,73,DivineTraube,8/15/2016 12:30
16239,10838945,PostgreSQL 9.5 Released,http://www.postgresql.org/message-id/E1aGCiB-0...,186,19,gdeglin,1/4/2016 21:48
16688,10444175,AMA with Greg Kemnitz (One of the Creators of ...,http://www.ama-live.com/#!/room/5623b05f2d3452...,8,1,sacheendra,10/24/2015 17:03
16925,12114429,Open Source NoSQL Database for .NET,http://www.alachisoft.com/nosdb/,1,1,youngdevangel,7/18/2016 11:28
17104,11340344,Potential Response to Oracles Anti-PostgreSQL ...,http://ded.ninja/dear_oracle/dear_oracle02.jpg,3,5,justinclift,3/22/2016 22:12
17207,12023517,PostgreSQL: the bits you haven't found,https://postgres-bits.herokuapp.com,13,3,cel1ne,7/2/2016 19:19
17660,12464343,Aurora RDS vs. Google CloudSQL Benchmark,http://2ndwatch.com/blog/benchmarking-amazon-a...,15,5,callmeradical,9/9/2016 17:32
17983,10707569,MySQL is a Better NoSQL,http://engineering.wix.com/2015/12/10/scaling-...,96,88,yoava,12/9/2015 23:18
17995,10810266,Ask HN: What are the best resources for learni...,NaN,4,2,foxhedgehog,12/30/2015 1:47
18063,12203959,Gh-ost: GitHub's online schema migration tool ...,http://githubengineering.com/gh-ost-github-s-o...,226,30,samlambert,8/1/2016 16:55
18072,11755358,"Show HN: ESENT Serialize, a .NET Persistence a...",https://github.com/Const-me/EsentSerialize,4,3,Const-me,5/23/2016 17:29
18166,10923848,"The Architecture of Schemaless, Uber Engineeri...",https://eng.uber.com/schemaless-part-two/,29,21,danielbryantuk,1/18/2016 11:49
18666,11502251,Parallel Query (PostgreSQL 9.6),https://wiki.postgresql.org/wiki/Parallel_Query,3,1,amitlan,4/15/2016 4:52
18828,12352831,Practical Guide to PostgreSQL Optimizations,https://tech.lendinghome.com/practical-guide-t...,124,16,omarish,8/24/2016 15:42
19066,12238169,A universal PHP script to generate JSON from a...,https://github.com/gautamkrishnar/unijson.php,2,1,gautamkrishnar,8/6/2016 14:13
19087,11662536,PostgreSQL Scalability: Towards Millions TPS,http://akorotkov.github.io/blog/2016/05/09/sca...,521,210,lneves,5/9/2016 19:41
19133,12041615,PostgreSQL: Linux VS Windows [Benchmark],http://www.sqig.net/2016/01/postgresql-linux-v...,2,3,insulanian,7/6/2016 7:01
19580,12252112,PostgreSQL Index Internals,https://www.pgcon.org/2016/schedule/events/934...,211,21,snaga,8/9/2016 2:09
19802,12223216,Uber's Move Away from PostgreSQL,http://rhaas.blogspot.com/2016/08/ubers-move-a...,119,15,ioltas,8/4/2016 3:36

In [9]:
hn_sql['flavor'] = hn_sql['title'].str.extract(r'(\w+SQL)',flags=re.I,expand=False)
hn_sql['flavor'].head()

142     PostgreSQL
221         MemSQL
882     PostgreSQL
1160         NoSQL
1197    PostgreSQL
Name: flavor, dtype: object

In [14]:
hn_sql['flavor'] =hn_sql['flavor'].str.lower()
sql_pivot = hn_sql.pivot_table(index='flavor',values='num_comments',aggfunc='mean')
sql_pivot

            num_comments
flavor
cloudsql        5.000000
memsql         14.000000
mysql          12.230769
nosql          14.529412
postgresql     25.962963
sparksql        1.000000

In [25]:
pattern = r'[Pp]ython ([\d\.]+)'
py_versions = titles.str.extract(pattern,expand=False)
py_versions_freq = dict(py_versions.value_counts())
print(py_versions.value_counts())
print(py_versions_freq)

3        10
3.5       3
2         3
3.6       2
8         1
1.5       1
2.7       1
4         1
3.5.0     1
Name: title, dtype: int64
{'3': 10, '3.5': 3, '2': 3, '3.6': 2, '8': 1, '1.5': 1, '2.7': 1, '4': 1, '3.5.0': 1}

In [26]:
def first_10_matches(pattern):
    """
    Return the first 10 story titles that match
    the provided regular expression
    """
    all_matches = titles[titles.str.contains(pattern)]
    first_10 = all_matches.head(10)
    return first_10

pattern = r'\b[Cc]\b[^+.]'
first_10 = first_10_matches(pattern)
first_10

365                      The new C standards are worth it
444           Moz raises $10m Series C from Foundry Group
521          Fuchsia: Micro kernel written in C by Google
1307            Show HN: Yupp, yet another C preprocessor
1326                     The C standard formalized in Coq
1365                          GNU C Library 2.23 released
1429    Cysignals: signal handling (SIGINT, SIGSEGV, )...
1620                        SDCC  Small Device C Compiler
1949    Rewriting a Ruby C Extension in Rust: How a Na...
2195    MyHTML  HTML Parser on Pure C with POSIX Threa...
Name: title, dtype: object

In [36]:
pattern = r'(?<!Series\s)\b[Cc]\b(?![+.]|\.$)'
#c_extract = titles.str.extract(pattern,expand=False) #ValueError: pattern contains no capture groups
#print(c_extract)
c_pattern =  titles.str.contains(pattern).value_counts()
print(c_pattern)
c_mentions = titles.str.contains(pattern).sum()
print(c_mentions)

False    19997
True       102
Name: title, dtype: int64
102

In [42]:
pattern = r'\b(\w+)\s\1\b'
repeated_words = titles[titles.str.contains(pattern)]
repeated_words

C:\Users\leo_w\anaconda3\lib\site-packages\pandas\core\strings.py:2001: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

3102                  Silicon Valley Has a Problem Problem
3176                Wire Wire: A West African Cyber Threat
3178                         Flexbox Cheatsheet Cheatsheet
4797                            The Mindset Mindset (2015)
7276     Valentine's Day Special: Bye Bye Tinder, Flirt...
10371    Mcdonalds copying cyriak  cows cows cows in th...
11575                                    Bang Bang Control
11901          Cordless Telephones: Bye Bye Privacy (1991)
12697          Solving the the Monty-Hall-Problem in Swift
15049    Bye Bye Webrtc2SIP: WebRTC with Asterisk and A...
15839          Intellij-Rust Rust Plugin for IntelliJ IDEA
Name: title, dtype: object

In [49]:
email_variations = pd.Series(['email', 'Email', 'e Mail',
                        'e mail', 'E-mail', 'e-mail',
                        'eMail', 'E-Mail', 'EMAIL'])

pattern = r"\be[\s-]*mail"

email_uniform = email_variations.str.replace(pattern, "email", flags=re.I)
titles_clean = titles.str.replace(pattern, "email",flags=re.I)
titles_clean

0                                Interactive Dynamic Video
1        Florida DJs May Face Felony for April Fools' W...
2             Technology ventures: From Idea to Enterprise
3        Note by Note: The Making of Steinway L1037 (2007)
4        Title II kills investment? Comcast and other I...
                               ...
20094    How Purism Avoids Intels Active Management Tec...
20095            YC Application Translated and Broken Down
20096    Microkernels are slow and Elvis didn't do no d...
20097                        How Product Hunt really works
20098    RoboBrowser: Your friendly neighborhood web sc...
Name: title, Length: 20099, dtype: object

In [50]:
test_urls = pd.Series([
 'https://www.amazon.com/Technology-Ventures-Enterprise-Thomas-Byers/dp/0073523429',
 'http://www.interactivedynamicvideo.com/',
 'http://www.nytimes.com/2007/11/07/movies/07stein.html?_r=0',
 'http://evonomics.com/advertising-cannot-maintain-internet-heres-solution/',
 'HTTPS://github.com/keppel/pinn',
 'Http://phys.org/news/2015-09-scale-solar-youve.html',
 'https://iot.seeed.cc',
 'http://www.bfilipek.com/2016/04/custom-deleters-for-c-smart-pointers.html',
 'http://beta.crowdfireapp.com/?beta=agnipath',
 'https://www.valid.ly?param',
 'http://css-cursor.techstream.org'
])

pattern = r'https?://([\w\-\.]+)'
test_urls_clean = test_urls.str.extract(pattern,expand=False,flags=re.I)
domains = hn['url'].str.extract(pattern,expand=False,flags=re.I)
top_domains = domains.value_counts().head()
top_domains

github.com             1008
medium.com              825
www.nytimes.com         525
www.theguardian.com     248
techcrunch.com          245
Name: url, dtype: int64

In [53]:
# `test_urls` is available from the previous screen
pattern = r'(https?)://([\w\-\.]+)/?(.*)'
test_url_parts = test_urls.str.extract(pattern,flags=re.I)
url_parts = hn['url'].str.extract(pattern,flags=re.I)
url_parts

,0,1,2
0,http,www.interactivedynamicvideo.com,
1,http,www.thewire.com,entertainment/2013/04/florida-djs-april-fools-...
2,https,www.amazon.com,Technology-Ventures-Enterprise-Thomas-Byers/dp...
3,http,www.nytimes.com,2007/11/07/movies/07stein.html?_r=0
4,http,arstechnica.com,business/2015/10/comcast-and-other-isps-boost-...
...,...,...,...
20094,https,puri.sm,philosophy/how-purism-avoids-intels-active-man...
20095,https,medium.com,@zreitano/the-yc-application-broken-down-and-t...
20096,http,blog.darknedgy.net,technology/2016/01/01/0/
20097,https,medium.com,@benjiwheeler/how-product-hunt-really-works-d8...
20098,https,github.com,jmcarp/robobrowser

In [54]:
pattern = r"(?P<protocol>https?)://(?P<domain>[\w\.\-]+)/?(?P<path>.*)"
url_parts = hn['url'].str.extract(pattern,flags=re.I)
url_parts

,protocol,domain,path
0,http,www.interactivedynamicvideo.com,
1,http,www.thewire.com,entertainment/2013/04/florida-djs-april-fools-...
2,https,www.amazon.com,Technology-Ventures-Enterprise-Thomas-Byers/dp...
3,http,www.nytimes.com,2007/11/07/movies/07stein.html?_r=0
4,http,arstechnica.com,business/2015/10/comcast-and-other-isps-boost-...
...,...,...,...
20094,https,puri.sm,philosophy/how-purism-avoids-intels-active-man...
20095,https,medium.com,@zreitano/the-yc-application-broken-down-and-t...
20096,http,blog.darknedgy.net,technology/2016/01/01/0/
20097,https,medium.com,@benjiwheeler/how-product-hunt-really-works-d8...
20098,https,github.com,jmcarp/robobrowser